# (17) Python program demonstrating list functions/methods

list_1= [10, 20, 30, 40,29,25]
print("Original List:", list_1)
print("Length:", len(list_1))
print("Count of 20:", list_1.count(20))
print("Index of 30:", list_1.index(30))
list_1.append(89)
print("After append(89):", list_1)
list_1.insert(2, 56)
print("After insert at index 2:", list_1)
list_1.extend([60, 70])
print("After extend:", list_1)
list_1.remove(25)
print("After remove 25:", list_1)
list_1.pop()
print("After pop():", list_1)
list_1.reverse()
print("After reverse():", list_1)
list_1.sort()
print("After sort():", list_1)
copy_list = list_1.copy()
print("Copied List:", copy_list)
list_1.clear()
print("After clear():", list_1)